// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Skillforge.Data;

#nullable disable

namespace Skillforge.Data.Migrations
{
    [DbContext(typeof(SkillForgeDB))]
    partial class SkillForgeDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Skillforge.Domain.Assessment", b =>
                {
                    b.Property<int>("AssessmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssessmentID"));

                    b.Property<int>("CourseID")
                        .HasColumnType("INT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("DATETIME");

                    b.Property<decimal>("MaxScore")
                        .HasPrecision(4, 1)
                        .HasColumnType("DECIMAL(4,1)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.HasKey("AssessmentID");

                    b.HasIndex("CourseID");

                    b.ToTable("Assessments", t =>
                        {
                            t.HasCheckConstraint("CK_Assessment_MaxScore", "[MaxScore] >= 0 AND [MaxScore] <= 100");

                            t.HasCheckConstraint("CK_Assessment_Type", "[Type] IN ('Quiz', 'Exam', 'Practical')");
                        });
                });

            modelBuilder.Entity("Skillforge.Domain.Attendance", b =>
                {
                    b.Property<int>("AttendanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceID"));

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("DATETIME");

                    b.Property<int>("EnrollmentID")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("AttendanceID");

                    b.HasIndex("EnrollmentID");

                    b.ToTable("Attendance");
                });

            modelBuilder.Entity("Skillforge.Domain.Audit", b =>
                {
                    b.Property<int>("AuditID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Findings")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HRID")
                        .HasColumnType("INT");

                    b.Property<int>("Scope")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("AuditID");

                    b.HasIndex("HRID");

                    b.ToTable("Audit");
                });

            modelBuilder.Entity("Skillforge.Domain.AuditLog", b =>
                {
                    b.Property<int>("AuditID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("UserID")
                        .HasColumnType("INT");

                    b.HasKey("AuditID");

                    b.HasIndex("UserID");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("Skillforge.Domain.Certification", b =>
                {
                    b.Property<int>("CertificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CertificationID"));

                    b.Property<int>("CourseID")
                        .HasColumnType("INT");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("INT");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.HasKey("CertificationID");

                    b.HasIndex("CourseID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("Certifications", t =>
                        {
                            t.HasCheckConstraint("CK_Certificate_Status", "[Status] IN ('Active', 'Revoked', 'Expired')");

                            t.HasCheckConstraint("CK_Certification_Dates", "[ExpiryDate] IS NULL OR [ExpiryDate] > [IssueDate]");
                        });
                });

            modelBuilder.Entity("Skillforge.Domain.Competency", b =>
                {
                    b.Property<int>("CompetencyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompetencyID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("VARCHAR(15)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10)");

                    b.HasKey("CompetencyID");

                    b.ToTable("Competency");
                });

            modelBuilder.Entity("Skillforge.Domain.ComplianceRecord", b =>
                {
                    b.Property<int>("ComplianceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComplianceID"));

                    b.Property<int>("CertificationID")
                        .HasColumnType("INT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("DATETIME");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("INT");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ComplianceID");

                    b.HasIndex("CertificationID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("ComplianceRecord");
                });

            modelBuilder.Entity("Skillforge.Domain.Course", b =>
                {
                    b.Property<int>("CourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<decimal>("Duration")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.Property<int>("TrainerID")
                        .HasColumnType("INT");

                    b.HasKey("CourseID");

                    b.HasIndex("TrainerID");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("Skillforge.Domain.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentID"));

                    b.Property<int>("CourseID")
                        .HasColumnType("INT");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("INT");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("EnrollmentID");

                    b.HasIndex("CourseID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("Enrollment");
                });

            modelBuilder.Entity("Skillforge.Domain.Module", b =>
                {
                    b.Property<int>("ModuleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModuleID"));

                    b.Property<string>("ContentURI")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<int>("CourseID")
                        .HasColumnType("INT");

                    b.Property<decimal>("Duration")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.HasKey("ModuleID");

                    b.HasIndex("CourseID");

                    b.ToTable("Module");
                });

            modelBuilder.Entity("Skillforge.Domain.Notification", b =>
                {
                    b.Property<int>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<int?>("CourseID")
                        .HasColumnType("INT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10)");

                    b.Property<int>("UserID")
                        .HasColumnType("INT");

                    b.HasKey("NotificationID");

                    b.HasIndex("CourseID");

                    b.HasIndex("UserID");

                    b.ToTable("Notification", t =>
                        {
                            t.HasCheckConstraint("CK_Notification_Status", "[Status] IN ('Unread', 'Read')");
                        });
                });

            modelBuilder.Entity("Skillforge.Domain.Report", b =>
                {
                    b.Property<int>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportID"));

                    b.Property<DateTime>("GeneratedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Metrics")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ScheduleID")
                        .HasColumnType("int");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.HasKey("ReportID");

                    b.HasIndex("ScheduleID");

                    b.ToTable("Report");
                });

            modelBuilder.Entity("Skillforge.Domain.ReportSchedule", b =>
                {
                    b.Property<int>("ScheduleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("INT");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastRun")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime?>("NextRun")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.HasKey("ScheduleID");

                    b.HasIndex("CreatedBy");

                    b.ToTable("ReportSchedule");
                });

            modelBuilder.Entity("Skillforge.Domain.Result", b =>
                {
                    b.Property<int>("AssessmentID")
                        .HasColumnType("INT");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("INT");

                    b.Property<int>("ResultID")
                        .HasColumnType("INT");

                    b.Property<decimal>("Score")
                        .HasPrecision(4, 1)
                        .HasColumnType("DECIMAL(4,1)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.HasKey("AssessmentID", "EmployeeID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("Results", t =>
                        {
                            t.HasCheckConstraint("CK_Result_Score", "[Score] >= 0 AND [Score] <= 100");

                            t.HasCheckConstraint("CK_Result_Status", "[Status] IN ('Pass', 'Fail')");
                        });
                });

            modelBuilder.Entity("Skillforge.Domain.SkillGap", b =>
                {
                    b.Property<int>("SkillGapID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillGapID"));

                    b.Property<int>("CompetencyID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateIdentified")
                        .HasColumnType("DATETIME");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("INT");

                    b.Property<int>("GapLevel")
                        .HasColumnType("int");

                    b.HasKey("SkillGapID");

                    b.HasIndex("CompetencyID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("SkillGap");
                });

            modelBuilder.Entity("Skillforge.Domain.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("UserID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Skillforge.Domain.Assessment", b =>
                {
                    b.HasOne("Skillforge.Domain.Course", "Course")
                        .WithMany("Assessments")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Skillforge.Domain.Attendance", b =>
                {
                    b.HasOne("Skillforge.Domain.Enrollment", "EnrollmentIdNavigation")
                        .WithMany("Attendances")
                        .HasForeignKey("EnrollmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnrollmentIdNavigation");
                });

            modelBuilder.Entity("Skillforge.Domain.Audit", b =>
                {
                    b.HasOne("Skillforge.Domain.User", "HRUser")
                        .WithMany("Audits")
                        .HasForeignKey("HRID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HRUser");
                });

            modelBuilder.Entity("Skillforge.Domain.AuditLog", b =>
                {
                    b.HasOne("Skillforge.Domain.User", "UserIdNavigation")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UserIdNavigation");
                });

            modelBuilder.Entity("Skillforge.Domain.Certification", b =>
                {
                    b.HasOne("Skillforge.Domain.Course", "Course")
                        .WithMany("Certifications")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skillforge.Domain.User", "UserRoleEmployee")
                        .WithMany("Certifications")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("UserRoleEmployee");
                });

            modelBuilder.Entity("Skillforge.Domain.ComplianceRecord", b =>
                {
                    b.HasOne("Skillforge.Domain.Certification", "Certification")
                        .WithMany()
                        .HasForeignKey("CertificationID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Skillforge.Domain.User", "Employee")
                        .WithMany("ComplianceRecords")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Certification");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Skillforge.Domain.Course", b =>
                {
                    b.HasOne("Skillforge.Domain.User", "UserIDNavigation")
                        .WithMany("Courses")
                        .HasForeignKey("TrainerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserIDNavigation");
                });

            modelBuilder.Entity("Skillforge.Domain.Enrollment", b =>
                {
                    b.HasOne("Skillforge.Domain.Course", "CourseIdNavigation")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skillforge.Domain.User", "EmployeeIdNavigation")
                        .WithMany("Enrollments")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CourseIdNavigation");

                    b.Navigation("EmployeeIdNavigation");
                });

            modelBuilder.Entity("Skillforge.Domain.Module", b =>
                {
                    b.HasOne("Skillforge.Domain.Course", "CourseIDNavigation")
                        .WithMany("Modules")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseIDNavigation");
                });

            modelBuilder.Entity("Skillforge.Domain.Notification", b =>
                {
                    b.HasOne("Skillforge.Domain.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Skillforge.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Skillforge.Domain.Report", b =>
                {
                    b.HasOne("Skillforge.Domain.ReportSchedule", "Schedule")
                        .WithMany("Reports")
                        .HasForeignKey("ScheduleID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Skillforge.Domain.ReportSchedule", b =>
                {
                    b.HasOne("Skillforge.Domain.User", "Admin")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("Skillforge.Domain.Result", b =>
                {
                    b.HasOne("Skillforge.Domain.Assessment", "Assessment")
                        .WithMany("Results")
                        .HasForeignKey("AssessmentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skillforge.Domain.User", "UserRoleEmployee")
                        .WithMany("Results")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assessment");

                    b.Navigation("UserRoleEmployee");
                });

            modelBuilder.Entity("Skillforge.Domain.SkillGap", b =>
                {
                    b.HasOne("Skillforge.Domain.Competency", "Competency")
                        .WithMany("SkillGaps")
                        .HasForeignKey("CompetencyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Skillforge.Domain.User", "Employee")
                        .WithMany("SkillGaps")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Competency");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Skillforge.Domain.Assessment", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("Skillforge.Domain.Competency", b =>
                {
                    b.Navigation("SkillGaps");
                });

            modelBuilder.Entity("Skillforge.Domain.Course", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("Certifications");

                    b.Navigation("Enrollments");

                    b.Navigation("Modules");
                });

            modelBuilder.Entity("Skillforge.Domain.Enrollment", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("Skillforge.Domain.ReportSchedule", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("Skillforge.Domain.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Audits");

                    b.Navigation("Certifications");

                    b.Navigation("ComplianceRecords");

                    b.Navigation("Courses");

                    b.Navigation("Enrollments");

                    b.Navigation("Results");

                    b.Navigation("SkillGaps");
                });
#pragma warning restore 612, 618
        }
    }
}
